version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    depends_on:
      - mitmproxy
    links:
      - mitmproxy:example.com

  mitmproxy:
    image: mitmproxy/mitmproxy
    container_name: mitmproxy
    entrypoint: "mitmweb -p 443 --web-host 0.0.0.0 --mode reverse:https://example.com"
    ports:
      - "8081:8081"
    expose:
      - 80
      - 443
